products-list/routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (){
    return redirect('products');
});

Route::get('/products', [HomeController::class, 'index'])->name('products');
Route::get('/product-list', [HomeController::class, 'edit'])->name('productsEdit');

// product's CRUD
Route::resource('products', ProductController::class)
    ->except(['index']);

products-list/app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'description',
        'price',
    ];
}

products-list/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

products-list/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

products-list/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;

/**
 * Class HomeController
 * @package App\Http\Controllers
 */
class HomeController extends Controller
{
    /**
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return response()->view('index', [
            'products' => Product::orderBy('updated_at', 'desc')->paginate(10),
            'title' => 'Products',
        ]);
    }

    /**
     * @return \Illuminate\Http\Response
     */
    public function edit()
    {
        return response()->view('index', [
            'products' => Product::orderBy('updated_at', 'desc')->paginate(10),
            'title' => 'Products edit',
            'edit' => true,
        ]);
    }
}

products-list/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

/**
 * Class ProductController
 * @package App\Http\Controllers
 */
class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view('productForm');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255',
            'price' => 'required|numeric|between:0.00,99999999.99|regex:/^\d+(\.\d{1,2})?$/',
            'description' => 'required',
        ]);

        if ($validator->fails()) {
            return redirect()->route('products.create')
                ->withErrors($validator)
                ->withInput();
        }

        $product = new Product([
            'name' => $request->name,
            'price' => $request->price,
            'description' => $request->description,
        ]);
        $product->save();

        return redirect()->route('productsEdit')->with([
            'flash' => 'Product created!'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param Product $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     * @param Product $product
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit(Product $product)
    {
        return view('productForm', [
            'product' => $product,
            'method' => 'PUT',
            'button' => 'Обновить',
            'route' => route('products.update', ['product' => $product->id]),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Product $product
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Product $product)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255',
            'price' => 'required|numeric|between:0.00,99999999.99|regex:/^\d+(\.\d{1,2})?$/',
            'description' => 'required',
        ]);

        if ($validator->fails()) {
            return redirect()->route('products.edit', ['product' => $product->id])
                ->withErrors($validator)
                ->withInput();
        }


        $product->fill([
            'name' => $request->name,
            'price' => $request->price,
            'description' => $request->description,
        ]);

        $product->save();

        return redirect()->route('productsEdit')->with([
            'flash' => 'Product updated!'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Product $product
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Product $product)
    {
        $product->delete();

        return redirect()->route('productsEdit')->with([
            'flash' => "Product with id={$product->id} deleted!"
        ]);
    }
}

products-list/resources/views/index.blade.php
@extends('layout')

@section('content')

    @include('products', ['products' => $products, 'title' => $title, 'edit' => $edit ?? null ])

@endsection

products-list/resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

        <title>Products</title>
    </head>
    <body>
    <div class="container">
        @include('navbar')

        @error('flash')
        <div class="alert alert-danger"> {{ $message }} </div>
        @enderror

        @if(session('flash'))
            <div class="alert alert-success"> {{ session('flash') }} </div>
        @endisset

        @yield('content')
    </div>


    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    </body>
</html>

products-list/resources/views/navbar.blade.php
@section('navbar')

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Products</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{{ route('products') }}">Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{{ route('productsEdit') }}">Products list</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
@show

products-list/resources/views/productForm.blade.php
@extends('layout')

@section('content')

    <p>Product form</p>

    <div class="row">

        <form action="{{ $route ?? route('products.store') }}" method="post">
            @csrf
            @if(!empty($method))
                <input name="_method" type="hidden" value="{{ $method }}">
            @endif

            @error('name')
            <hr>
            <div class="alert alert-danger"> {{ $message }} </div>
            @enderror
            <div class="mb-3">
                <label for="name" class="form-label">Name</label>
                <input type="text" class="form-control" id="name"
                       name="name" placeholder="Name"
                       value="{{ old('name') ?? $product->name ?? '' }}">
            </div>

            @error('price')
            <hr>
            <div class="alert alert-danger"> {{ $message }} </div>
            @enderror
            <div class="mb-3">
                <label for="price" class="form-label">Price</label>
                <input type="text" class="form-control" id="price" name="price" placeholder="price"
                       value="{{ old('price') ?? $product->price ?? '' }}">
            </div>

            @error('description')
            <hr>
            <div class="alert alert-danger"> {{ $message }} </div>
            @enderror
            <div class="mb-3">
                <label for="description" class="form-label">Description</label>
                <textarea class="form-control" id="description" name="description" rows="3">{{ old('description')  ?? $product->description ?? ''}}</textarea>
            </div>

            <button type="submit" class="btn btn-success">{{ $button ?? 'Создать'}}</button>
        </form>
    </div>


@endsection

products-list/resources/views/productView.blade.php
@extends('layout')

@section('content')

    <p>Product details</p>

    <div class="row">

            <div class="col">
                <div class="card">
                    <div class="card-body">

                            <h5 class="card-title">Product id: {{ $product->id }}</h5>
                            <h5 class="card-text">Product name: {{ $product->name }}</h5>
                            <h5 class="card-text">Description: {{ $product->description }}</h5>
                            <h5 class="card-text">Price: {{ $product->price }}</h5>

                        <a href="{{ route('products.edit', ['product' => $product->id]) }}" class="btn btn-success">Редактировать</a>
                        <form action="{{ route('products.destroy', ['product' => $product->id]) }}" method="post">
                            @csrf
                            <input name="_method" type="hidden" value="DELETE">
                            <button type="submit" class="btn btn-danger">Удалить</button>
                        </form>

                    </div>
                </div>
            </div>

    </div>


@endsection

products-list/resources/views/products.blade.php
<div class="row">

    <h2>{{ $title }}</h2>

    @isset($edit)
        <div class="col mb-3">
            <a href="{{ route('products.create') }}" class="btn btn-success">Создать новый</a>
        </div>

    @endisset

    <div class="row mb-3">
        {{ $products->links() }}
    </div>

    <table class="table table-striped">
        <thead class="thead-light">
        <tr>
            <th scope="col">id</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Price</th>
            <th scope="col">Date</th>
            @isset($edit)
            <th scope="col">Edit</th>
            @endisset
        </tr>
        </thead>
        <tbody>
        @forelse ($products as $key => $product)
            <tr>
                <th scope="row">{{ $product->id }}</th>
                <td>{{ $product->name }}</td>
                <td>{{ $product->description }}</td>
                <td>{{ $product->price }}</td>
                <td>{{ $product->updated_at }}</td>
                @isset($edit)
                <th scope="col">
                    <a href="{{ route('products.edit', ['product' => $product->id]) }}" class="btn btn-success">Редактировать</a>
                    <form action="{{ route('products.destroy', ['product' => $product->id]) }}" method="post">
                        @csrf
                        <input name="_method" type="hidden" value="DELETE">
                        <button type="submit" class="btn btn-danger">Удалить</button>
                    </form>
                </th>
                @endisset
            </tr>
        @empty
            <tr>
                <td colspan="6">No products</td>
            </tr>
        @endforelse
        </tbody>
    </table>

    <div class="row mb-3">
        {{ $products->links() }}
    </div>
</div>